### ISSUE TITLE
Make MK work on Windows

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#1410]
The dependencies of MK already compile for Windows. What is missing to have a Windows version of MK is the possibility of compiling MK itself on Windows. This should not be complicated, because MK is written in portable C++14 that is supported by the Windows compiler. This ticket is about to list the tasks required to have a fully functional MK library on Windows. I will start sketching out what are the main issues to solve and iterate over updating the issue, and possibly also create more-specific issues.

- [ ] improving the cross building system to easily recompile and package dependencies for Windows system (this is equivalent to have `./build/dependency` working for them).

- [ ] improve CMake and the code such that we can produce a DLL for Windows where we export only the symbols required to implement desktop apps (it is unclear at this point where we really need a DLL or whether just a static library would do, but generally producing a DLL seems just like right).

- [x] identify places in the code where we need better abstractions beyond what is currently supported on Unix. Path composing abstractions come to mind, and here the objective is basically to understand whether we need to keep this abstraction in MK and, if this is true, find out proper portable replacements rather than relying on ghetto code. This can probably by solved either by requiring C++17 (that has abstractions related to the file system) or by perhaps using libapr (see #981) &mdash; maybe only for Windows.

- [ ] add testing support, probably via Appveyor, so we know that tests work on Windows. I also think it would be useful to have something Valgrind like to have more confidence that we are working correctly on Windows.

- [ ] explore the possibility to make the DLL available via [Chocolatey](https://chocolatey.org/).

There is an old PR that was attempting to start having an MK for Windows. This is #820.

**Comment by bassosimone** [comment]
Even though we did not follow the original plan described above, we've now done enough work to make MK work on Windows that we can call this Epic done. Further work will mainly focus on refining stuff but the great bulk of the work needed to have a Windows ready MK is now done.

(It has not been easy, but it's done!!!)
