### ISSUE TITLE
regression: not all tests have a top-level failure key

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#1761]
It seems #1759 is wrong. Not all tests have a failure key. Some tests have nested failures but generally we do not have a regular way of deciding whether a test succeeded or not. This is heavily dependent on the type of the test. So, the real solution is probably to enforce a schema in MK. It goes without saying that `v0.9.5` is wrong and #1759 should be reverted. My bad 😞.

Spotted when smoke testing for Android and reading the logs. Happy at least that trying to have a more formal release process has been helpful to spot this issue.

**Comment by bassosimone** [comment]
This is how I am going to address this issue:

- [ ] will revert #1759 in master (see #1762)

- [ ] will revert #1759 in stable and push directly to stable

- [ ] will flag `v0.9.5` as an unstable release and amend the commit message pointing people to `v0.9.4`, which is the correct release (shall we need any new release from the `stable` branch, we already have reverted the offending commit, so we're good)

- [ ] will make sure that @lorenzoPrimi and @xanscale know that I've screwed it up and they should not wait for `v0.9.5` to be released, because it's a wrong release, and they should use `v0.9.4`

- [ ] will reopen the original issue and assign it to `v0.11.0` adding details on why the fix attempted in #1759 was wrong and what could be done instead

- [ ] finally close this issue and continue working on `v0.10.0` (which will land soon)

**Comment by lorenzoPrimi** [comment]
Did you release android or iOS libs with `v0.9.5 ` ? If yes which ones are the versions to avoid?

**Comment by bassosimone** [comment]
@lorenzoPrimi I did not. I noticed the issue after compiling for Android and when testing such binaries on a simulator. I did mention you and @xanscale just to let you know that you don’t need to wait for MK to make a new mobile release.

**Comment by bassosimone** [comment]
@lorenzoPrimi I did not. I noticed the issue after compiling for Android and when testing such binaries on a simulator. I did mention you and @xanscale just to let you know that you don’t need to wait for MK to make a new mobile release.

**Comment by bassosimone** [comment]
I have completed the above check list. This issue will be closed now.
