### ISSUE TITLE
story: faster development cycles

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#1867]
During the development cycle of OONI mobile v2.1.0, the fact that we vendor into MK a bunch of files that we don't use in MK slowed down the process. These files are used only by mobile apps, therefore, it would be more proper to vendor them in mkall-ios and android-libs.

If we implement this change, any improvement to the way in which we resubmit the measurements, e.g., would only entail recompiling mkall-ios and android-libs. Since their build is significantly faster than a MK build, this would enable more velocity.

Additionally, I noticed that we're writing C wrappers for C++ code that doesn't actually need such wrappers, because the macro system we use can be easily adapted to use the C++ code in ObjectiveC and Java. Therefore, this also brings to the table the opportunity of getting rid of a bunch of code that we don't actually need.

This is the list of tasks that we need to complete to make this change effective:

- [x] remove the non-required files from MK v0.10.5 [#1868]

- [x] make sure we use inline versioned namespaces to make sure we can mix and match different versions of the library for testing purposes without breakages. Ideally, this should be done on a library per library basis without the need to add it everywhere, because what we really need is just the functionality that we can have, say, a version of MK compiled with mkcurl v0.11.0 and the possibility to inline mkcurl v0.11.2 (say) to make sure we can have a good API for mobile without releasing all and recompiling MK before being able to evaluate the new API. So, the likely candidates for this change are just the libraries that are currently bundled with MK. See https://github.com/measurement-kit/mkcurl/pull/36 and https://github.com/measurement-kit/measurement-kit/issues/1867#issuecomment-514562622.

- [x] make sure any significant glue in C code is not lost by moving what is needed directly to the header-only C++ libraries such as `mkcollector.hpp` [#1869]

- [ ] modify mkall-ios to vendor the required headers and use them properly [measurement-kit/mkall-ios#24]

- [ ] modify android-libs to vendor the required headers and use them properly [measurement-kit/android-libs#77]

**Comment by bassosimone** [comment]
# On using inline namespaces

My original plan was to allow the user to change the inline namespace. When using this change in, e.g., measurement-kit/mkcurl#36 and measurement-kit/mkall-ios#25, I realised that this was not so practical to do. Therefore, I'm just adding an inline namespace to avoid conflicting symbols as well as to avoid making tracebacks more complex to read.

**Comment by bassosimone** [comment]
I'm going to call this done. Some further work is required in the Android and iOS repos but there is no need to keep track of that from here.
