### ISSUE TITLE
Roadmap for improving mlab-ns implementation

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#399]
- [x] use a real JSON library (perhaps [nlohmann/json](https://github.com/nlohmann/json)) rather than yaml-cpp to parse results (see #463)
- [x] implement https and use https to access mlabns
- [x] add some regress tests (#465)

**Comment by AntonioLangiu** [comment]
This should be closed! @bassosimone
