### ISSUE TITLE
Improving our NDT client

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#400]
- [x] understand the feasibility of wrapping NDT using a C++11 interface and then proceeding in small steps to evolve each phase of the test to be asynchronous
- [x] merge connect-many (#467)
- [x]  merge initial implementation of NDT client (#441)
- [x] teach the client to wait in queue
- [x] merge full fledged NDT client
- [x] save results into a json-ish structure
- [ ] write regress test verifying that we can read messages we serialize
- [ ] close connection if test version is too old
- [ ] introduce specific error for each failed test rather than "a test failed" error
- [ ] protect against functions calling themselves "forever" using a counter
- [ ] send more metadata to server (what specifically?)
- [ ] terminate download coroutine if the server seems to have gone wild and sends data "forever"
- [ ] implement the WebSockets transport
- [ ] make sure we can run WebSockets over TLS

**Comment by bassosimone** [comment]
We're not going to continue improving the ndt client in MK. The future is ndt7 and we'll expose it to OONI apps using ooni/probe-engine.
