### ISSUE TITLE
Refactoring of ooni implementation

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#557]
- [x] merge input-file-generator as a function of ooni plus an input stream as an attribute
- [x] unify logic for setting common attributes for with and without input tests
- [X] file-reporter should be more asynchronous (_for now in #654 I've modified the code such that Error eventually reported by this code cannot be ignored. There is no need to make it asynchronous for now because we're not actually using asynchronous code inside it_)
- [X] make report public by removing reference to `json` in its methods signature (_see #627 and following commits_)
- [ ] refactor callbacks to have `Error` as first argument (see also #455)
- [ ] the `main()` should be a `Delegate<T>` to facilitate testing
  - [ ] related to the previous point, the non-delegate part (i.e. running with single input or iterating over input or running with `nullptr` input) should be merged back inside `common/net_test.hpp` such that other tests could benefit from that
- [ ] implement a runner for the test
- [ ] allow executing the test on a single input (_being worked on in #660_)
- [X] implement code to talk to the collector (_see #655_)

**Comment by bassosimone** [comment]
This is an old issue that was keeping track of a refactoring occurring more than two years ago.
