### ISSUE TITLE
Release cycle: v0.3.x

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#712]
- [x] Fix TLS timeout bug (#711)
- [x] HTTP client should support following redirects (#561)
- [x] Implement web_connectivity test (#682) (#690)
- [x] Logger: allow to write logs onto a file (#706)
- [x] ndt: optionally use ooni collector (#681)
- [x] ndt: store results in a json file (#680)
- [x] ndt: add mlab-server to test_keys (#721)
- [x] update dependencies (#731)
- [x] Add settings required by NetProbe (#713)
- [x] ndt: implement support for waiting in queue (#679)
- [x] add cli interface (#559)
- [x] Implement incremental ooni collector (#669)
- [x] Run ooni tests in parallel (#768)
- [x] beta release (#771)

---
- [x] possibly backport small patches
- [x] close already openned minor issues
- [x] check whether we need to update dependencies again
  - [x] geoip: no
  - [x] libevent: yes
  - [x] libressl: yes
  - [x] nlohmann/json: yes
  - [x] philsquared/Catch: yes
  - [x] nodejs/http-parser: no
  - [x] tls_verify.c: yes
  - [x] portable/strnum.c: no
- [ ] code review
  - [x] headers
  - [ ] source
  - [ ] tests
- [ ] update documentation
- [x] tag release
- [ ] build dependencies for:
  - [x] android
  - [ ] windows
  - [x] ios
- [ ] build packages for:
  - [x] macosx
  - [ ] windows
  - [x] debian
  - [x] android (developer's pack)
- [x] update apps:
  - [x] netprobe-android
  - [x] netprobe-ios
  - [x] simple-ios-app

**Comment by bassosimone** [comment]
Well, I think I performed most tasks attached to this release cycle. Furthermore, release-0.4.0 is approaching and for this reason I'll close this issue and from now on focus on 0.4.0
