### ISSUE TITLE
Release v0.3.4

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#881]
- [x] switch over to using b.collector.test.ooni.io (#880)
- [x] remove ./build/android/library and update documentation (#870)
- [x] completely address (fixing web_connectivity for good) #867 
- [x] update version and changelog using `./build/release`

**Comment by bassosimone** [comment]
Well, the release was published, closing
