### ISSUE TITLE
measurement-kit v0.7.0

### ISSUE THREAD

**Issue by bassosimone** [measurement-kit/measurement-kit#906]
- [ ] ooni: implement header manipulation test (#692)
- [ ] ooni: find out user's ip using duckduckgo's api (#775)
- [ ] merge dash test
- [ ] integration with ooni

**Comment by bassosimone** [comment]
Since `v0.7.0` is out, we can close this epic!
